from .idiotAgent import idiotModel
from .debugAgent import debugModel
from .dqn_agent import dqnModel
from .allfoldAgent import allFoldModel
from .allcallAgent import allCallModel
from .allinAgent import allinModel
from .allraiseAgent import allRaiseModel
from .udqnAgent import UdqnModel
from .CdqnAgent import CdqnModel
from .hodorAgent import WinRateGambler